spring:
  datasource:
    url: jdbc:h2:mem:testDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always


  # JPA properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate.format_sql: true
      hibernate:
        show_sql: true
    generate-ddl: false


remote:
  url: "https://www.arbeitnow.com/api/job-board-api"