server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:jobboard
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2


  # JPA properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate.format_sql: true
      hibernate:
        show_sql: true


remote:
    url: "https://www.arbeitnow.com/api/job-board-api"

