name: CD
on:
 workflow_run:
    workflows: CI
    branches: [master]
    types:
      - completed
jobs:
  artifact-creation:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: set up JDK from Matrix
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: package project
        run: mvn -DskipTests=true package
      - name: save artifact to Github actions
        uses: actions/upload-artifact@v4
        with:
          name: jobBoard_jar
          path: target/jobBoardApi-0.0.1-SNAPSHOT.jar
      - name: get jobBoard_jar artifact
        uses: actions/download-artifact@v4
        with:
          name: jobBoard_jar
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn -DskipTests=true package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_CREDENTIALS_USR }}
          password: ${{ secrets.DOCKERHUB_CREDENTIALS_PSW }}
      - name: build and push Docker image
        run: | 
         docker build . -t alekckorsh/jobboardapi
         docker push alekckorsh/jobboardapi:latest
