name: CI
on: workflow_dispatch
jobs:
  artifact-creation:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: set up JDK from Matrix
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: package project
        run: mvn -DskipTests=true package
      - name: save artifact to Github actions
        uses: actions/upload-artifact@v4
        with:
          name: jobBoard_jar
          path: target/jobBoardApi-0.0.1-SNAPSHOT.jar
      - name: get jobBoard_jar artifact
        uses: actions/download-artifact@v4
        with:
          name: jobBoard_jar
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - run: mvn -DskipTests=true package
      - name: build Docker image
        run: docker build . -t alekckorsh/hospital
