  name: test stage
  on: push
  jobs:
    test:
       runs-on: ubuntu-latest
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK 11
           uses: actions/setup-java@v4
           with:
             distribution: 'temurin'
             java-version: '17'
             architecture: x64
         - name: clean and compile project with Maven
           run: mvn clean compile
         - name: run integration tests
           run: mvn verify
         - name: package project
           run: mvn -DskipTests=true package
