  name: test stage
  on: push
  jobs:
    test:
       runs-on: ubuntu-latest
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK 11
           uses: actions/setup-java@v4
           with:
             distribution: 'temurin'
             java-version: '17'
             architecture: x64
         - name: clean and package project with Maven wrapper
           run: mvn --batch-mode --update-snapshots clean package
         - name: verify integration-tests with Maven wrapper
           run: mvn verify
