  name: CI
  on: push
  jobs:
    cache:
      runs-on: ubuntu-latest
      steps:
        - name: get repository code
          uses: actions/checkout@v4
        - name: set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
    test:
       needs: cache
       runs-on: ubuntu-latest
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK 17
           uses: actions/setup-java@v4
           with:
             distribution: 'temurin'
             java-version: '17'
             cache: 'maven'
         - name: clean and compile project with Maven
           run: mvn clean compile
         - name: run integration tests
           run: mvn verify
    package:
       needs: test
       runs-on: ubuntu-latest
       continue-on-error: true
       strategy:
         matrix:
           java: ['11', '17', '21' ]
       name: Java ${{ matrix.Java }} sample
       steps:
         - name: get repository code
           uses: actions/checkout@v4
         - name: set up JDK 17
           uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}
            cache: 'maven'
         - name: package project
           run: mvn -DskipTests=true package
